language: ruby
rvm:
  - 2.4.4
before_script:
  - cp config/database.example.yml config/database.yml
  - sed -e 's/# username/username/' -e 's/# password/password/' -i config/database.yml
  - rake db:setup
