default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  # username: postgres
  # password:

development:
  <<: *default
  database: hermes_dev

test:
  <<: *default
  database: hermes_test

production:
  <<: *default
  database: hermes_prod
